name: 清理旧工作流

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "编译 ImmortalWrt 固件"
    types:
      - completed

jobs:
  cleanup:
    name: 清理旧数据
    runs-on: ubuntu-22.04

    steps:
      - name: 删除旧的工作流运行记录
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GH_TOKEN }}
          retain_days: 7
          keep_minimum_runs: 0

      - name: 删除旧的发布版本
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 15
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
