name: X86_64 Parallel Build

on:
  workflow_dispatch:
  # schedule:
  #   - cron: 0 22 * * *

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: master
  DIY_FEEDS: diy-feeds.sh
  INIT_SCRIPT: patch/init-settings.sh
  PATCH_SCRIPT: patch/fix_version_error.sh
  MAKE_SCRIPT: scripts/retry-make.sh
  CACHE_TOOLCHAIN: true
  UPLOAD_BIN_DIR: false
  FIRMWARE_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  Info:
    runs-on: ubuntu-22.04
    outputs:
      OPENWRT_PATH: ${{ steps.clone.outputs.OPENWRT_PATH }}
      SOURCE_REPO: ${{ steps.generate.outputs.SOURCE_REPO }}
      DEVICE_TARGET: ${{ steps.generate.outputs.DEVICE_TARGET }}
      DEVICE_SUBTARGET: ${{ steps.generate.outputs.DEVICE_SUBTARGET }}
      COMMIT_AUTHOR: ${{ steps.clone.outputs.COMMIT_AUTHOR }}
      COMMIT_DATE: ${{ steps.clone.outputs.COMMIT_DATE }}
      COMMIT_MESSAGE: ${{ steps.clone.outputs.COMMIT_MESSAGE }}
      COMMIT_HASH: ${{ steps.clone.outputs.COMMIT_HASH }}
      USE_APK: ${{ steps.generate.outputs.USE_APK }}
    steps:
    - name: æ£€æŸ¥æœºå™¨æ€§èƒ½
      run: |
        echo "è­¦å‘Šâš "
        echo "åˆ†é…çš„æœåŠ¡å™¨æ€§èƒ½æœ‰é™ï¼Œè‹¥é€‰æ‹©çš„æ’ä»¶è¿‡å¤šï¼ŒåŠ¡å¿…æ³¨æ„CPUæ€§èƒ½ï¼"
        echo -e "å·²çŸ¥CPUå‹å·(é™åº): 7763ï¼Œ8370Cï¼Œ8272CLï¼Œ8171Mï¼ŒE5-2673\n"
        echo "--------------------------CPUä¿¡æ¯--------------------------"
        echo "CPUç‰©ç†æ•°é‡: $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
        echo "CPUæ ¸å¿ƒæ•°é‡: $(nproc)"
        echo -e "CPUå‹å·ä¿¡æ¯:$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
        echo "--------------------------å†…å­˜ä¿¡æ¯--------------------------"
        echo "å·²å®‰è£…å†…å­˜è¯¦ç»†ä¿¡æ¯:"
        echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
        echo "--------------------------ç¡¬ç›˜ä¿¡æ¯--------------------------"
        echo "ç¡¬ç›˜æ•°é‡: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

    - name: é‡Šæ”¾ç£ç›˜ç©ºé—´
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false
        
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: æ¸…ç†å‰
      run: |
        set -xe
        df -H

    - name: æ¸…ç†ä¸­
      run: |
        set -xe
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/share/swift
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo rm -rf /opt/hostedtoolcache/
        sudo rm -rf /usr/local/graalvm/
        sudo rm -rf /usr/local/share/powershell
        sudo rm -rf /usr/local/share/chromium
        sudo rm -rf /usr/local/lib/node_modules
        sudo docker image prune --all --force
        
        APT_PARAMS='sudo apt -y -qq -o=Dpkg::Use-Pty=0'
        $APT_PARAMS remove -y '^dotnet-.*'
        $APT_PARAMS remove -y '^llvm-.*'
        $APT_PARAMS remove -y '^php.*'
        $APT_PARAMS remove -y '^mongodb-.*'
        $APT_PARAMS remove -y '^mysql-.*'
        $APT_PARAMS remove -y azure-cli google-* google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri
        $APT_PARAMS autoremove --purge -y
        $APT_PARAMS autoclean
        $APT_PARAMS clean
      
  
    - name: åˆå§‹åŒ–ç¯å¢ƒ
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -y update
        sudo -E apt-get -y install scdoc ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool llvm lrzsz msmtp ninja-build p7zip p7zip-full patch pkgconf python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo -E systemctl daemon-reload
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get -y clean
        sudo timedatectl set-timezone "$TZ"

    - name: åˆå¹¶ç£ç›˜
      uses: easimon/maximize-build-space@master
      with:
        swap-size-mb: 1024
        temp-reserve-mb: 100
        root-reserve-mb: 1024
    
    - name: ç£ç›˜ä¿¡æ¯
      run: |
        set -xe
        df -H

    - name: æ£€æŸ¥
      uses: actions/checkout@main

    - name: å…‹éš†ä»“åº“
      id: clone
      run: |
        chmod +x $GITHUB_WORKSPACE/scripts/*
        chmod +x $GITHUB_WORKSPACE/patch/*
        chmod +x $GITHUB_WORKSPACE/diy-*.sh
        df -hT $GITHUB_WORKSPACE
        git clone -b $REPO_BRANCH --single-branch --filter=blob:none $REPO_URL openwrt
        cd openwrt
        echo "OPENWRT_PATH=$PWD" >> $GITHUB_ENV
        echo "OPENWRT_PATH=$PWD" >> $GITHUB_OUTPUT
        COMMIT_AUTHOR=$(git show -s --date=short --format="ä½œè€…: %an")
        echo "COMMIT_AUTHOR=$COMMIT_AUTHOR" >> $GITHUB_ENV
        echo "COMMIT_AUTHOR=$COMMIT_AUTHOR" >> $GITHUB_OUTPUT
        COMMIT_DATE=$(git show -s --date=short --format="æ—¶é—´: %ci")
        echo "COMMIT_DATE=$COMMIT_DATE" >> $GITHUB_ENV
        echo "COMMIT_DATE=$COMMIT_DATE" >> $GITHUB_OUTPUT
        COMMIT_MESSAGE=$(git show -s --date=short --format="å†…å®¹: %s")
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
        COMMIT_HASH=$(git show -s --date=short --format="hash: %H")
        echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
        echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_OUTPUT

    - name: ç”Ÿæˆå˜é‡
      id: generate
      run: |
        cd $OPENWRT_PATH
        SOURCE_REPO="$(echo $REPO_URL | awk -F '/' '{print $(NF)}')"
        echo "SOURCE_REPO=$SOURCE_REPO" >> $GITHUB_ENV
        echo "SOURCE_REPO=$SOURCE_REPO" >> $GITHUB_OUTPUT
        DEVICE_TARGET=$(cat .config | grep CONFIG_TARGET_BOARD | awk -F '"' '{print $2}')
        echo "DEVICE_TARGET=$DEVICE_TARGET" >> $GITHUB_ENV
        echo "DEVICE_TARGET=$DEVICE_TARGET" >> $GITHUB_OUTPUT
        DEVICE_SUBTARGET=$(cat .config | grep CONFIG_TARGET_SUBTARGET | awk -F '"' '{print $2}')
        echo "DEVICE_SUBTARGET=$DEVICE_SUBTARGET" >> $GITHUB_ENV
        echo "DEVICE_SUBTARGET=$DEVICE_SUBTARGET" >> $GITHUB_OUTPUT
        if grep -q "^CONFIG_USE_APK=y$" .config; then
            echo "USE_APK=true" >> $GITHUB_ENV
            echo "USE_APK=true" >> $GITHUB_OUTPUT
        else
            echo "USE_APK=false" >> $GITHUB_ENV
            echo "USE_APK=false" >> $GITHUB_OUTPUT
        fi

    - name: ç¼“å­˜å·¥å…·é“¾
      if: env.CACHE_TOOLCHAIN == 'true'
      uses: HiGarfield/cachewrtbuild@main
      with:
        ccache: false
        mixkey: ${{ env.SOURCE_REPO }}-${{ env.REPO_BRANCH }}-${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}
        prefix: ${{ env.OPENWRT_PATH }}

    - name: å®‰è£… Feed å¹¶åŠ è½½ Patch
      run: |
        cd $OPENWRT_PATH
        $GITHUB_WORKSPACE/patch/update_eth.sh
        $GITHUB_WORKSPACE/$DIY_FEEDS
        ./scripts/feeds update -a
        # $GITHUB_WORKSPACE/$PATCH_SCRIPT
        ./scripts/feeds install -a

  Build-Full:
    needs: Info
    runs-on: ubuntu-22.04
    env:
      OPENWRT_PATH: ${{ needs.Info.outputs.OPENWRT_PATH }}
      SOURCE_REPO: ${{ needs.Info.outputs.SOURCE_REPO }}
      DEVICE_TARGET: ${{ needs.Info.outputs.DEVICE_TARGET }}
      DEVICE_SUBTARGET: ${{ needs.Info.outputs.DEVICE_SUBTARGET }}
      USE_APK: ${{ needs.Info.outputs.USE_APK }}
      FIRMWARE_TAG: X86_64_Full_ImmortalWrt
    steps:
    - name: æ£€æŸ¥
      uses: actions/checkout@main

    - name: åŠ è½½è‡ªå®šä¹‰é…ç½®
      run: |
        [ -e files ] && mv files $OPENWRT_PATH/files
        [ -e configs/x86_64-immortalWrt.config ] && cp configs/x86_64-immortalWrt.config $OPENWRT_PATH/.config
        cd $OPENWRT_PATH
        $GITHUB_WORKSPACE/diy-full.sh

    - name: ä¸‹è½½ä¾èµ–
      run: |
        cd $OPENWRT_PATH
        make defconfig
        $GITHUB_WORKSPACE/$MAKE_SCRIPT download
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: ç¼–è¯‘å›ºä»¶
      id: compile
      run: |
        cd $OPENWRT_PATH
        mkdir -p files/etc/uci-defaults
        cp $GITHUB_WORKSPACE/$INIT_SCRIPT files/etc/uci-defaults/99-init-settings
        echo -e "$(nproc) thread compile"
        $GITHUB_WORKSPACE/$MAKE_SCRIPT nproc || make -j$(nproc) V=s
        echo "status=success" >> $GITHUB_OUTPUT
        echo "DATE=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
        echo "FILE_DATE=$(date +"%Y.%m.%d")" >> $GITHUB_ENV

    - name: æ£€æŸ¥ç£ç›˜ç©ºé—´
      if: (!cancelled())
      run: df -hT

    - name: ä¸Šä¼ äºŒè¿›åˆ¶æ–‡ä»¶
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      uses: actions/upload-artifact@main
      with:
        name: ${{ env.SOURCE_REPO }}-bin-${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}-${{ env.FILE_DATE }}-Full
        path: ${{ env.OPENWRT_PATH }}/bin

    - name: æ•´ç†æ–‡ä»¶
      if: steps.compile.outputs.status == 'success'
      run: |
        cd $OPENWRT_PATH/bin/targets/*/*
        cat sha256sums
        cp $OPENWRT_PATH/.config build.config
        if [ "${{ env.USE_APK }}" = "true" ]; then
          mv -f $OPENWRT_PATH/bin/packages/*/*/*.apk packages
        else
          mv -f $OPENWRT_PATH/bin/packages/*/*/*.ipk packages
        fi
        tar -zcf Packages.tar.gz packages
        rm -rf packages feeds.buildinfo version.buildinfo
        echo "KERNEL=$(jq -r '.linux_kernel.version // "unknown"' profiles.json)" >> $GITHUB_ENV
        echo "FIRMWARE_PATH=$PWD" >> $GITHUB_ENV

    - name: ä¸Šä¼ å›ºä»¶è‡³ Artifact
      if: steps.compile.outputs.status == 'success' && env.FIRMWARE_RELEASE != 'true'
      uses: actions/upload-artifact@main
      with:
        name: ${{ env.SOURCE_REPO }}-firmware-${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}-${{ env.FILE_DATE }}-Full
        path: ${{ env.FIRMWARE_PATH }}

    - name: ä¸Šä¼ å›ºä»¶è‡³ Release
      if: steps.compile.outputs.status == 'success' && env.FIRMWARE_RELEASE == 'true'
      uses: softprops/action-gh-release@v2
      with:
        name: R${{ env.FILE_DATE }}_${{ env.FIRMWARE_TAG }}
        tag_name: R${{ env.FILE_DATE }}_${{ env.FIRMWARE_TAG }}
        token: ${{ secrets.GH_TOKEN }}
        files: ${{ env.FIRMWARE_PATH }}/*
        body: |
          **This is OpenWrt Firmware for ${{ env.FIRMWARE_TAG }}**
          ### ğŸ“’ å›ºä»¶ä¿¡æ¯
          - ğŸ’» å¹³å°æ¶æ„: ${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}
          - âš½ å›ºä»¶æºç : ${{ env.REPO_URL }}
          - ğŸ’ æºç åˆ†æ”¯: ${{ env.REPO_BRANCH }}
          - ğŸš€ å†…æ ¸ç‰ˆæœ¬: ${{ env.KERNEL }}
          - ğŸŒ é»˜è®¤åœ°å€: 192.168.1.1
          - ğŸ”‘ é»˜è®¤å¯†ç : 
          ### ğŸ§Š å›ºä»¶ç‰ˆæœ¬
          - å›ºä»¶ç¼–è¯‘å‰æœ€åä¸€æ¬¡â¦[ä¸»æºç ](${{ env.REPO_URL }})æ›´æ–°è®°å½•
          - ${{ needs.Info.outputs.COMMIT_AUTHOR }}
          - ${{ needs.Info.outputs.COMMIT_DATE }}
          - ${{ needs.Info.outputs.COMMIT_MESSAGE }}
          - ${{ needs.Info.outputs.COMMIT_HASH }}

  Build-Mini:
    needs: Info
    runs-on: ubuntu-22.04
    env:
      OPENWRT_PATH: ${{ needs.Info.outputs.OPENWRT_PATH }}
      SOURCE_REPO: ${{ needs.Info.outputs.SOURCE_REPO }}
      DEVICE_TARGET: ${{ needs.Info.outputs.DEVICE_TARGET }}
      DEVICE_SUBTARGET: ${{ needs.Info.outputs.DEVICE_SUBTARGET }}
      USE_APK: ${{ needs.Info.outputs.USE_APK }}
      FIRMWARE_TAG: X86_64_Mini_ImmortalWrt
    steps:
    - name: æ£€æŸ¥
      uses: actions/checkout@main

    - name: åŠ è½½è‡ªå®šä¹‰é…ç½®
      run: |
        [ -e configs/x86_64-immortalWrt-mini.config ] && cp configs/x86_64-immortalWrt-mini.config $OPENWRT_PATH/.config
        cd $OPENWRT_PATH
        $GITHUB_WORKSPACE/diy-mini.sh

    - name: ä¸‹è½½ä¾èµ–
      run: |
        cd $OPENWRT_PATH
        make defconfig
        $GITHUB_WORKSPACE/$MAKE_SCRIPT download
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: ç¼–è¯‘å›ºä»¶
      id: compile
      run: |
        cd $OPENWRT_PATH
        mkdir -p files/etc/uci-defaults
        cp $GITHUB_WORKSPACE/$INIT_SCRIPT files/etc/uci-defaults/99-init-settings
        echo -e "$(nproc) thread compile"
        $GITHUB_WORKSPACE/$MAKE_SCRIPT nproc || make -j$(nproc) V=s
        echo "status=success" >> $GITHUB_OUTPUT
        echo "DATE=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
        echo "FILE_DATE=$(date +"%Y.%m.%d")" >> $GITHUB_ENV

    - name: æ£€æŸ¥ç£ç›˜ç©ºé—´
      if: (!cancelled())
      run: df -hT

    - name: ä¸Šä¼ äºŒè¿›åˆ¶æ–‡ä»¶
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      uses: actions/upload-artifact@main
      with:
        name: ${{ env.SOURCE_REPO }}-bin-${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}-${{ env.FILE_DATE }}-Mini
        path: ${{ env.OPENWRT_PATH }}/bin

    - name: æ•´ç†æ–‡ä»¶
      if: steps.compile.outputs.status == 'success'
      run: |
        cd $OPENWRT_PATH/bin/targets/*/*
        cat sha256sums
        cp $OPENWRT_PATH/.config build.config
        if [ "${{ env.USE_APK }}" = "true" ]; then
          mv -f $OPENWRT_PATH/bin/packages/*/*/*.apk packages
        else
          mv -f $OPENWRT_PATH/bin/packages/*/*/*.ipk packages
        fi
        tar -zcf Packages.tar.gz packages
        rm -rf packages feeds.buildinfo version.buildinfo
        echo "KERNEL=$(jq -r '.linux_kernel.version // "unknown"' profiles.json)" >> $GITHUB_ENV
        echo "FIRMWARE_PATH=$PWD" >> $GITHUB_ENV

    - name: ä¸Šä¼ å›ºä»¶è‡³ Artifact
      if: steps.compile.outputs.status == 'success' && env.FIRMWARE_RELEASE != 'true'
      uses: actions/upload-artifact@main
      with:
        name: ${{ env.SOURCE_REPO }}-firmware-${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}-${{ env.FILE_DATE }}-Mini
        path: ${{ env.FIRMWARE_PATH }}

    - name: ä¸Šä¼ å›ºä»¶è‡³ Release
      if: steps.compile.outputs.status == 'success' && env.FIRMWARE_RELEASE == 'true'
      uses: softprops/action-gh-release@v2
      with:
        name: R${{ env.FILE_DATE }}_${{ env.FIRMWARE_TAG }}
        tag_name: R${{ env.FILE_DATE }}_${{ env.FIRMWARE_TAG }}
        token: ${{ secrets.GH_TOKEN }}
        files: ${{ env.FIRMWARE_PATH }}/*
        body: |
          **This is OpenWrt Firmware for ${{ env.FIRMWARE_TAG }}**
          ### ğŸ“’ å›ºä»¶ä¿¡æ¯
          - ğŸ’» å¹³å°æ¶æ„: ${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}
          - âš½ å›ºä»¶æºç : ${{ env.REPO_URL }}
          - ğŸ’ æºç åˆ†æ”¯: ${{ env.REPO_BRANCH }}
          - ğŸš€ å†…æ ¸ç‰ˆæœ¬: ${{ env.KERNEL }}
          - ğŸŒ é»˜è®¤åœ°å€: 192.168.1.1
          - ğŸ”‘ é»˜è®¤å¯†ç : 
          ### ğŸ§Š å›ºä»¶ç‰ˆæœ¬
          - å›ºä»¶ç¼–è¯‘å‰æœ€åä¸€æ¬¡â¦[ä¸»æºç ](${{ env.REPO_URL }})æ›´æ–°è®°å½•
          - ${{ needs.Info.outputs.COMMIT_AUTHOR }}
          - ${{ needs.Info.outputs.COMMIT_DATE }}
          - ${{ needs.Info.outputs.COMMIT_MESSAGE }}
          - ${{ needs.Info.outputs.COMMIT_HASH }}